### ISSUE TITLE
Throw an error if node.js is too old for the plugin

### ISSUE THREAD

**Issue by peternewman** [wikimedia/grunt-stylelint#101]
I don't really know if this is an issue for this grunt plugin, or should be upstream in grunt or node.js or somewhere else, but I've been trying to migrate some CI and usage of the grunt-stylelint plugin stopped working. After a lot of debugging I've found we were running node v8.12.0 which hasn't been supported in stylelint since 12.0.1 apparently: https://github.com/stylelint/stylelint/issues/4787#issuecomment-630118186

Nothing in the whole stack threw any errors, despite the fact you all seem to have the engines bit set in packages.json, so does nothing actually read it? See the source issue:
https://github.com/OpenLightingProject/ola/issues/1733

Some Google suggests it's user error, is there really no sensible way to catch and warn of this by default, I've wasted a few hours on it:
https://npm.community/t/engines-and-engines-strict-ignored/4792

**Comment by peternewman** [comment]
I think this can probably be closed given https://github.com/npm/npm/issues/12486 unless there is some easy way to check within the plugin to save people time?

**Comment by jdforrester** [comment]
Hmm. I think theoretically we could write something here that does an environment check before proceeding, but that definitely feels like something that should be done by node/npm itself, not us, I agree. 

(Also, such a feature should probably be if not in node/npm at least in stylelint itself and not this wrapper for it.)

Closing without prejudice for now.

**Comment by peternewman** [comment]
Yeah fair enough. I eventually worked out the cause of my issue as being that anyway.
