### ISSUE TITLE
Add support for stylelint's --max-warnings

### ISSUE THREAD

**Issue by umherirrender** [wikimedia/grunt-stylelint#123]
Setting an option in Gruntfile.js with maxWarnings: 0 would be nice

```lang=js
		stylelint: {
			options: {
				reportNeedlessDisables: true,
				maxWarnings: 0            // <!---------- new
			},
			src: '{resources/src,mw-config}/**/*.{css,less,vue}'
		},
```

https://stylelint.io/user-guide/options/#maxwarnings

Supported by grunt-eslint
https://www.npmjs.com/package/grunt-eslint#Options

**Comment by edg2s** [comment]
We pass through all options by default, so this should already work...
