### ISSUE TITLE
Add output/export options

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [wikimedia/grunt-stylelint#26]
Hi there, 

would be great if you can define an output file or export the logs to: 
- a normal text file
- a JSON file 

Currently you only can get the output in the console.

**Comment by jdforrester** [comment]
With #31 you can now pass in `formatter: "json"` to output into JSON. However, I think for your ask of outputting to a file it'd be better to just use output piping than put a feature into the tool. FWICT other grunt tools don't provide an output-to-file option either.

**Comment by jdforrester** [comment]
We've now with #35 (thanks @crudo!) got the ability to output to a file. Doesn't come out in JSON or a custom formatted file though… Is that enough?

**Comment by Sebastian-Fitzner** [comment]
I think so, will take a look. Nice!
