### ISSUE TITLE
Add force option

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [wikimedia/grunt-stylelint#27]
A real enhancement would be an option called `forced` which give us the possibility to complete the whole task.

**Comment by jdforrester** [comment]
I'm not sure I understand. If there are multiple issues they all get flagged, not just the first one or in the first file; if you want to continue despite the error `grunt stylelint --force` will do that. Sorry, I'm missing something, I'm sure?

**Comment by jdforrester** [comment]
In doing #35 we added `failOnError` (defaulting to true), so deeming this fixed in the next release.

**Comment by Sebastian-Fitzner** [comment]
Thx, nice work
