### ISSUE TITLE
Example Configuration

### ISSUE THREAD

**Issue by bitstarr** [wikimedia/grunt-stylelint#29]
I would love to see a grunt config example in the readme. I'm just a frontend dev an not soo keen in node development, so i'm pretty left alone with your current usage description :(

**Comment by Sebastian-Fitzner** [comment]
I can provide an example for you. Here you go: 

```js
stylelint: {
	scss: {
		options: {
			configFile: 'helpers/task-configs/stylelint.config.js',
			format: 'scss'
		},
		src: [
			'src/scss/**/*.scss',
			'!src/scss/styles.scss'
		]
	}
}
```

Have a nice day.

**Comment by jdforrester** [comment]
The original use of this was in https://github.com/wikimedia/oojs-ui/blob/master/Gruntfile.js#L351 — will see if I can add something a tad simpler, though.

**Comment by bitstarr** [comment]
Thanks for the help. It's simpler than i thought, but i head no idea how to start with this.

Th snippet of @Sebastian-Fitzner and maybe a bit help about the possible options will be enought documentation to start.

**Comment by ntwb** [comment]
Rather than `format: 'scss'` shouldn't that be `syntax: 'scss'`?

**Comment by Volker-E** [comment]
@bitstarr With a5ea1e6 merged, is this ready to be resolved?

**Comment by bitstarr** [comment]
Well, the example above is much more verbose than the one in the merge :(

**Comment by Volker-E** [comment]
@bitstarr Don't understand your last comment, being more verbose in giving examples is not in your interest?

**Comment by bitstarr** [comment]
Sorry, the example in the merge is not giving so much information about the options as the example of @Sebastian-Fitzner in this thread.

**Comment by superclarkk** [comment]
@Volker-E , I agree with @bitstarr , @Sebastian-Fitzner 's example is a lot clearer than the one in https://github.com/wikimedia/grunt-stylelint/commit/a5ea1e6bff30d2ad3e79eee4ad624f9b8af63073.
