### ISSUE TITLE
latest stylelint-config-wikimedia and grunt-stylelint incompatibility

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/grunt-stylelint#32]
I updated
-    "stylelint-config-wikimedia": "0.2.2",
+    "stylelint-config-wikimedia": "0.3.0",

-    "grunt-stylelint": "^0.4.0",
+    "grunt-stylelint": "^0.6.0",

Running "stylelint:all" (stylelint) task
Warning: Running stylelint failed
Error: Undefined rule media-query-parentheses-space-inside
    at exports.default (/Users/jrobson/git/weekapedia/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /Users/jrobson/git/weekapedia/node_modules/stylelint/dist/augmentConfig.js:267:43
    at Array.forEach (native)
    at normalizeAllRuleSettings (/Users/jrobson/git/weekapedia/node_modules/stylelint/dist/augmentConfig.js:263:29)
    at /Users/jrobson/git/weekapedia/node_modules/stylelint/dist/augmentConfig.js:91:12 Use --force to continue.

Aborted due to warnings.

**Comment by ntwb** [comment]
The stylelint rule `media-query-parentheses-space-inside` was replaced in stylelint 7.0.0 with `media-feature-parentheses-space-inside`.

You should create an issue/pull request at https://github.com/wikimedia/stylelint-config-wikimedia/ to raise and/or fix the issue

p.s. This issue can be closed, it's a `stylelint-config-wikimedia` configuration issue

**Comment by Volker-E** [comment]
This was already fixed in https://github.com/wikimedia/stylelint-config-wikimedia/commit/ecfa1654ec996eeb13dadb68a062ebd3cca107f1#diff-168726dbe96b3ce427e7fedce31bb0bc 
We'll gonna tag new version in a bit.
