### ISSUE TITLE
Stylelint as peerDependency not installed

### ISSUE THREAD

**Issue by josephrace** [wikimedia/grunt-stylelint#46]
Can you explain why you recently chose to move stylelint from `dependencies` to `peerDependencies`?

Peer dependencies are no longer automatically installed as of npm@3 (http://blog.npmjs.org/post/110924823920/npm-weekly-5) which means that I now see an `UNMET PEER DEPENDENCY` warning for stylelint and this plugin doesn't work.

Did you intend for the user to install stylelint manually themselves? If so the Readme file should probably be updated.

**Comment by ntwb** [comment]
There is some background in #42 

As to the issue itself, I myself don't know the pros and cons of peer deps without researching it 😏

**Comment by josephrace** [comment]
Thanks, that's interesting!

As @jdforrester mentioned, most other similar packages for Grunt/Gulp (including the Gulp equivalent to this one - `gulp-stylelint`) now use `dependencies` rather than `peerDependencies`.

I don't have a great deal of experience publishing my own packages so I'm not fully fully aware of the pros/cons either, but it seems that this is a move which npm has encouraged.  My instinct would be to follow convention and aim to provide the same user experience as those other packages.

**Comment by jdforrester** [comment]
> Did you intend for the user to install stylelint manually themselves?

Yes.

> If so the Readme file should probably be updated.

Good point, sorry about that.
