### ISSUE TITLE
Please update dependency to latest stylelint 7.10.1

### ISSUE THREAD

**Issue by jitendravyas** [wikimedia/grunt-stylelint#48]
https://github.com/stylelint/stylelint/releases/tag/7.10.1

**Comment by jitendravyas** [comment]
It's 7.11.1 now  https://github.com/stylelint/stylelint/releases/tag/7.11.1

**Comment by Samic8** [comment]
8.0.0 is not available

**Comment by ntwb** [comment]
> 8.0.0 is not available

It sure is @Samic8 https://github.com/stylelint/stylelint/releases/tag/8.0.0

**Comment by jdforrester** [comment]
Done via #54. Release coming soon.

**Comment by RinkAttendant6** [comment]
9.1 is now available
