### ISSUE TITLE
Error: undefined does not match any files

### ISSUE THREAD

**Issue by Th3S4mur41** [wikimedia/grunt-stylelint#50]
When working with filter (I use a filter to only verify staged files), stylelint throws an error when there is no file to verify.

```
        eslint: {
            staged: {
                files: [
                    {
                        expand: true,
                        src:[
                            'scripts/**/*.js'
                        ],
                        filter: function(filepath) {
                            // do some filtering
                            return found;
                        }
                    }
                ]
            }
        },
```

> Warning: Running stylelint failed
> Error: undefined does not match any files
>   at globby.then.filePaths (D:\src\uc_webclient\src\client_revision\ui\node_modules\stylelint\lib\standalone.js:128:33)
>   at <anonymous>:null:null
>   at process._tickCallback (internal/process/next_tick.js:169:7)
>   at Function.Module.runMain (module.js:607:11)
>   at startup (bootstrap_node.js:158:16)
>   at bootstrap_node.js:575:3
>  Use --force to continue.
> 
> Aborted due to warnings.

It should just display a message like "No Files specified" (behavior from guntify-eslint) instead and not abort with an error

**Comment by tgr** [comment]
Can be avoided with a config like

    stylelint: {
        options: {
            allowEmptyInput: true
        },
        all: [
            '**/*.{css,less}',
        ]
    }

See stylelint/stylelint#2048.

**Comment by jdforrester** [comment]
I'd rather not try to exhaustively copy-and-paste upstream's config options in our README, but at the same time just implicitly saying RTFM isn't very helpful. :-) Do you think this is worth calling out explicitly?

**Comment by tgr** [comment]
Yes, it's not very well documented (the `--help` output is the only place where it is mentioned I think).

**Comment by jdforrester** [comment]
Moved to our new task venue in https://phabricator.wikimedia.org/T364160
