### ISSUE TITLE
Empty Output in Mac OS Terminal

### ISSUE THREAD

**Issue by ikennai** [wikimedia/grunt-stylelint#58]
Attempting to use grunt-stylelint however the output in mac terminal is blank.  I saw the same issue was previously closed unresolved. Resubmitting.
![screen shot 2018-03-05 at 1 09 28 am](https://user-images.githubusercontent.com/32691096/36966595-1c9c8546-2012-11e8-89f3-d29d3f3402e8.png)

**Comment by rettgerst** [comment]
I'm seeing this same issue, also on a mac, but using iTerm2 and not the stock macOS Terminal.app.

node v9.6.1
grunt-cli v1.2.0
grunt v1.0.2
stylelint 9.1.1
grunt-stylelint 0.9.0

**Comment by tenub** [comment]
Same issue here, using iTerm2 on macOS 10.13.2 and the same versions as above (except node 9.7.1).

**Comment by Volker-E** [comment]
Reopened #49, closing this.
