### ISSUE TITLE
Use stylelint's built-in formatters

### ISSUE THREAD

**Issue by jeddy3** [wikimedia/grunt-stylelint#9]
Hello. Thanks for making a start on `grunt-stylelint`. It's a missing piece of the stylelint eco-system!

It's looking great so far. I have one suggestion though. I think you'll want to use stylelint's [built-in formatters](https://github.com/stylelint/stylelint/tree/master/src/formatters). The [default "string" formatter](https://github.com/stylelint/stylelint/blob/master/src/formatters/stringFormatter.js) is [quite powerful](https://cloud.githubusercontent.com/assets/808227/14970067/063e5802-10be-11e6-8774-6557d80c443b.png) and, I believe, the main reason someone would want to use a dedicated stylelint grunt plugin, rather than use the existing `grunt-postcss` and `postcss-reporter` combo.

Perhaps have a look at how [`grunt-eslint`](https://github.com/sindresorhus/grunt-eslint) passes [along its options](https://github.com/sindresorhus/grunt-eslint/blob/master/tasks/eslint.js#L27-L32) to eslint itself. You'll find stylelint's Node API options documented [here](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#options).

Thanks again and please don't hesitate to ask if you've any questions about the stylelint Node API :)

**Comment by jdforrester** [comment]
Hey, thanks. This seems like it'd be a neat improvement, and would help. Note that a large part of our objective with this was to more neatly tie into grunt's formatting model, so I'll need to work out how to combine the best of both. :-)

**Comment by jeddy3** [comment]
> This seems like it'd be a neat improvement, and would help

Good stuff :)

> Note that a large part of our objective with this was to more neatly tie into grunt's formatting model

Perhaps bundle [a custom formatter](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/formatters.md) that adheres to grunt's formatting model with this plugin?
