### ISSUE TITLE
Is --fix available as an option in Gruntfile.js?

### ISSUE THREAD

**Issue by davemoz** [wikimedia/grunt-stylelint#91]
Is it possible to implement the `--fix` flag when using grunt-stylelint? I'm not seeing or finding an option to enable it in my Gruntfile.js.

Or is there a different recommended way to auto-fix with stylelint?

Thanks

**Comment by davemoz** [comment]
I'm ending up using an IDE extension that includes auto-fix support, but leaving this comment as it may be useful to know for others or in the future.

**Comment by edg2s** [comment]
The stylelint Node API can be passed a `fix` option (https://stylelint.io/user-guide/usage/options). That would be pretty easy to pass through here from `grunt.option( 'fix' )`.
